import axios from 'axios';

// ============================================================
// CREATIVE ENGINE
// Génère automatiquement : hooks, scripts, copy ads, landing pages
// A/B testing visuel, adaptation multi-pays
// Utilise OpenAI GPT-4 pour la génération de texte
// ============================================================

export interface CreativeHook {
  text: string;
  type: 'question' | 'statement' | 'shock' | 'benefit' | 'social_proof';
  platform: string;
  estimated_ctr: number;
}

export interface AdScript {
  hook: string;
  problem: string;
  agitation: string;
  solution: string;
  proof: string;
  cta: string;
  duration_seconds: number;
  platform: string;
}

export interface AdCopy {
  headline: string;
  primary_text: string;
  description: string;
  cta: string;
  platform: string;
  character_count: number;
}

export interface LandingPageContent {
  hero_title: string;
  hero_subtitle: string;
  benefits: string[];
  social_proof: string;
  guarantee: string;
  cta_primary: string;
  cta_secondary: string;
  faq: { question: string; answer: string }[];
}

export interface ABTestVariant {
  id: string;
  name: string;
  hook: string;
  headline: string;
  estimated_ctr: number;
  status: 'running' | 'winner' | 'loser' | 'pending';
}

export class CreativeEngine {
  private openaiKey: string;
  private openaiUrl = 'https://api.openai.com/v1/chat/completions';

  constructor(openaiKey?: string) {
    this.openaiKey = openaiKey || process.env.OPENAI_API_KEY || '';
  }

  private async callGPT(prompt: string, maxTokens = 800): Promise<string> {
    if (!this.openaiKey) {
      // Mode simulation si pas de clé API
      return this.simulateGPT(prompt);
    }
    try {
      const res = await axios.post(
        this.openaiUrl,
        {
          model: 'gpt-4-turbo-preview',
          messages: [
            { role: 'system', content: 'You are an expert direct-response copywriter and media buyer with 10+ years experience in e-commerce. Write in the specified language. Be concise, punchy, and conversion-focused.' },
            { role: 'user', content: prompt }
          ],
          max_tokens: maxTokens,
          temperature: 0.8,
        },
        { headers: { Authorization: 'Bearer ' + this.openaiKey, 'Content-Type': 'application/json' } }
      );
      return res.data.choices[0].message.content.trim();
    } catch (error) {
      console.error('OpenAI error:', error);
      return this.simulateGPT(prompt);
    }
  }

  private simulateGPT(prompt: string): string {
    // Fallback simulation quand pas de clé OpenAI
    if (prompt.includes('hook')) return 'This changed my life in 30 days — here is what I did differently';
    if (prompt.includes('script')) return 'Hook | Problem | Solution | Proof | CTA — generated script';
    if (prompt.includes('landing')) return 'Transform your results with our proven system';
    return 'Creative content generated by AEGIS AI';
  }

  // ─── GÉNÉRATION HOOKS ────────────────────────────────────────

  async generateHooks(product: string, target: string, platform: string, count = 5): Promise<CreativeHook[]> {
    const prompt = `Generate ${count} high-converting hooks for: "${product}" targeting "${target}" on ${platform}.
    
    Rules:
    - Max 15 words each
    - Mix types: question, shock, benefit, social proof, statement
    - No emojis in first 3 words
    - Direct response style
    
    Return as JSON array: [{"text": "...", "type": "question|shock|benefit|social_proof|statement"}]`;

    try {
      const raw = await this.callGPT(prompt, 600);
      const parsed = JSON.parse(raw.replace(/```json?/g, '').replace(/```/g, '').trim());
      return parsed.map((h: any, i: number) => ({
        ...h,
        platform,
        estimated_ctr: parseFloat((1.5 + Math.random() * 4).toFixed(2)),
      }));
    } catch {
      return this.generateFallbackHooks(product, platform, count);
    }
  }

  private generateFallbackHooks(product: string, platform: string, count: number): CreativeHook[] {
    const types = ['question', 'benefit', 'shock', 'social_proof', 'statement'];
    const templates = [
      'Did you know ' + product + ' can change your life in 30 days?',
      'Stop wasting money on ' + product + ' that does not work',
      '50,000 customers already transformed with ' + product,
      product + ' users see results in just 7 days',
      'The real reason most people fail at ' + product,
    ];
    return templates.slice(0, count).map((text, i) => ({
      text,
      type: types[i % types.length] as any,
      platform,
      estimated_ctr: parseFloat((1.5 + Math.random() * 4).toFixed(2)),
    }));
  }

  // ─── GÉNÉRATION SCRIPTS VIDÉO ────────────────────────────────

  async generateVideoScript(product: string, duration: 15 | 30 | 60, platform: string): Promise<AdScript> {
    const prompt = `Write a ${duration}-second video ad script for "${product}" on ${platform}.
    
    Use PAS (Problem-Agitate-Solution) + proof + CTA structure.
    Keep it punchy and visual-first.
    
    Return as JSON: {
      "hook": "opening line (first 3 seconds)",
      "problem": "pain point (5-8 seconds)",
      "agitation": "make pain worse (5-8 seconds)",
      "solution": "introduce product (8-12 seconds)",
      "proof": "social proof or result (5-8 seconds)",
      "cta": "call to action (2-3 seconds)"
    }`;

    try {
      const raw = await this.callGPT(prompt, 600);
      const parsed = JSON.parse(raw.replace(/```json?/g, '').replace(/```/g, '').trim());
      return { ...parsed, duration_seconds: duration, platform };
    } catch {
      return {
        hook: 'I was struggling with [problem] until I found ' + product,
        problem: 'Every day you waste time and money on solutions that do not work.',
        agitation: 'Meanwhile, your competitors are already using what actually works.',
        solution: product + ' solves this in minutes, not months.',
        proof: 'Over 10,000 happy customers — 4.9 stars average.',
        cta: 'Click below. Limited stock available.',
        duration_seconds: duration,
        platform,
      };
    }
  }

  // ─── GÉNÉRATION COPY ADS ─────────────────────────────────────

  async generateAdCopy(product: string, platform: string, language = 'fr'): Promise<AdCopy[]> {
    const prompt = `Generate 3 ad copy variants for "${product}" on ${platform} in ${language}.
    
    For each variant return: headline (max 40 chars), primary_text (max 150 chars), description (max 30 chars), cta.
    
    Return as JSON array of 3 objects.`;

    try {
      const raw = await this.callGPT(prompt, 800);
      const parsed = JSON.parse(raw.replace(/```json?/g, '').replace(/```/g, '').trim());
      return parsed.map((c: any) => ({
        ...c,
        platform,
        character_count: (c.primary_text || '').length,
      }));
    } catch {
      return [
        { headline: product + ' — Résultats garantis', primary_text: 'Des milliers de clients satisfaits. Livraison rapide. Retours faciles. Essayez maintenant sans risque.', description: 'Offre limitée', cta: 'Acheter maintenant', platform, character_count: 95 },
        { headline: 'Transformez vos résultats', primary_text: 'Découvrez pourquoi ' + product + ' est le choix n°1. Plus de 50 000 clients. Note 4.9/5.', description: 'Livraison offerte', cta: 'Voir l offre', platform, character_count: 88 },
        { headline: 'Économisez 30% aujourd hui', primary_text: 'Promotion exclusive sur ' + product + '. Stock limité. Profitez-en avant la fin de l offre.', description: product, cta: 'Commander', platform, character_count: 82 },
      ];
    }
  }

  // ─── GÉNÉRATION LANDING PAGE ─────────────────────────────────

  async generateLandingPage(product: string, targetAudience: string, mainBenefit: string): Promise<LandingPageContent> {
    const prompt = `Create a high-converting landing page content for "${product}".
    Target: ${targetAudience}. Main benefit: ${mainBenefit}.
    
    Return as JSON with: hero_title, hero_subtitle, benefits (array of 4), social_proof, guarantee, cta_primary, cta_secondary, faq (array of 3 with question and answer).`;

    try {
      const raw = await this.callGPT(prompt, 1000);
      return JSON.parse(raw.replace(/```json?/g, '').replace(/```/g, '').trim());
    } catch {
      return {
        hero_title: mainBenefit + ' avec ' + product,
        hero_subtitle: 'Rejoignez ' + targetAudience + ' qui ont déjà transformé leurs résultats',
        benefits: ['Résultats visibles rapidement', 'Simple à utiliser', 'Garanti ou remboursé', 'Support client réactif'],
        social_proof: '+10 000 clients satisfaits • Note 4.9/5',
        guarantee: 'Satisfait ou remboursé 30 jours — aucun risque',
        cta_primary: 'Commander maintenant',
        cta_secondary: 'Voir les avis clients',
        faq: [
          { question: 'Quand vais-je voir des résultats ?', answer: 'La plupart des clients voient des résultats dès les 7 premiers jours.' },
          { question: 'Et si ça ne fonctionne pas pour moi ?', answer: 'Remboursement complet garanti sous 30 jours, sans question posée.' },
          { question: 'Comment est la livraison ?', answer: 'Livraison en 2-5 jours ouvrés. Gratuite à partir de 40€.' },
        ],
      };
    }
  }

  // ─── A/B TESTING VISUEL AUTOMATIQUE ─────────────────────────

  async createABTest(product: string, platform: string): Promise<ABTestVariant[]> {
    const hooks = await this.generateHooks(product, 'general audience', platform, 3);
    const copies = await this.generateAdCopy(product, platform);

    return hooks.slice(0, 3).map((hook, i) => ({
      id: 'variant_' + String.fromCharCode(65 + i),
      name: 'Variante ' + String.fromCharCode(65 + i),
      hook: hook.text,
      headline: copies[i]?.headline || hook.text.substring(0, 40),
      estimated_ctr: hook.estimated_ctr,
      status: 'pending' as const,
    }));
  }

  // ─── ADAPTATION MULTI-PAYS ───────────────────────────────────

  async adaptForCountry(copy: AdCopy, targetCountry: string): Promise<AdCopy> {
    const countryLanguages: Record<string, string> = {
      FR: 'French', DE: 'German', ES: 'Spanish', IT: 'Italian',
      UK: 'English (British)', US: 'English (American)', BR: 'Portuguese (Brazilian)',
    };
    const lang = countryLanguages[targetCountry] || 'French';
    const prompt = `Translate and culturally adapt this ad copy to ${lang} for ${targetCountry}:
    
    Headline: ${copy.headline}
    Primary text: ${copy.primary_text}
    CTA: ${copy.cta}
    
    Keep the same persuasion structure. Adapt cultural references. Return JSON with same fields.`;

    try {
      const raw = await this.callGPT(prompt, 400);
      const adapted = JSON.parse(raw.replace(/```json?/g, '').replace(/```/g, '').trim());
      return { ...copy, ...adapted, platform: copy.platform + '_' + targetCountry };
    } catch {
      return { ...copy, platform: copy.platform + '_' + targetCountry };
    }
  }
}

export default CreativeEngine;
