export const mockAgents = [
    {
        id: 'agent-001',
        name: 'content-creator',
        displayName: 'Content Creator',
        description: 'Generates high-quality, engaging content tailored to platform requirements',
        role: 'content_creation',
        status: 'active',
        capabilities: ['content_generation', 'platform_optimization', 'hashtag_research', 'tone_adaptation'],
        dependencies: [],
        isPremium: false,
        isEnabled: true,
        created_at: '2026-01-15T10:00:00Z',
        updated_at: '2026-02-01T08:00:00Z',
        task_count: 1254,
        success_rate: 97,
        error_count: 38,
        avg_duration_ms: 2340,
        last_execution_at: '2026-02-01T07:45:00Z',
    },
    {
        id: 'agent-002',
        name: 'social-optimizer',
        displayName: 'Social Optimizer',
        description: 'Optimizes campaigns and posts for maximum engagement and reach',
        role: 'optimization',
        status: 'active',
        capabilities: ['performance_analysis', 'optimization_recommendation', 'a_b_testing', 'engagement_boost'],
        dependencies: ['content-creator'],
        isPremium: false,
        isEnabled: true,
        created_at: '2026-01-15T10:00:00Z',
        updated_at: '2026-02-01T07:30:00Z',
        task_count: 892,
        success_rate: 95,
        error_count: 45,
        avg_duration_ms: 1850,
        last_execution_at: '2026-02-01T07:30:00Z',
    },
    {
        id: 'agent-003',
        name: 'budget-analyzer',
        displayName: 'Budget Analyzer',
        description: 'Analyzes and optimizes ad spend across platforms',
        role: 'analytics',
        status: 'active',
        capabilities: ['budget_analysis', 'spend_optimization', 'roi_calculation', 'forecast'],
        dependencies: [],
        isPremium: false,
        isEnabled: true,
        created_at: '2026-01-15T10:00:00Z',
        updated_at: '2026-02-01T08:15:00Z',
        task_count: 1567,
        success_rate: 98,
        error_count: 31,
        avg_duration_ms: 3200,
        last_execution_at: '2026-02-01T08:15:00Z',
    },
    {
        id: 'agent-004',
        name: 'competitor-intel',
        displayName: 'Competitor Intelligence',
        description: 'Monitors and analyzes competitor strategies and trends',
        role: 'intelligence',
        status: 'active',
        capabilities: ['competitor_tracking', 'trend_analysis', 'strategy_comparison', 'market_insights'],
        dependencies: [],
        isPremium: true,
        isEnabled: true,
        created_at: '2026-01-16T14:00:00Z',
        updated_at: '2026-02-01T06:00:00Z',
        task_count: 423,
        success_rate: 94,
        error_count: 25,
        avg_duration_ms: 4500,
        last_execution_at: '2026-02-01T06:00:00Z',
    },
    {
        id: 'agent-005',
        name: 'customer-engagement',
        displayName: 'Customer Engagement',
        description: 'Manages customer interactions and engagement across platforms',
        role: 'engagement',
        status: 'active',
        capabilities: ['response_generation', 'sentiment_analysis', 'customer_segmentation', 'personalization'],
        dependencies: ['content-creator'],
        isPremium: false,
        isEnabled: true,
        created_at: '2026-01-17T09:00:00Z',
        updated_at: '2026-02-01T07:50:00Z',
        task_count: 2341,
        success_rate: 96,
        error_count: 94,
        avg_duration_ms: 1200,
        last_execution_at: '2026-02-01T07:50:00Z',
    },
    {
        id: 'agent-006',
        name: 'conversion-optimizer',
        displayName: 'Conversion Optimizer',
        description: 'Optimizes funnels and conversion rates',
        role: 'conversion',
        status: 'active',
        capabilities: ['funnel_analysis', 'conversion_optimization', 'landing_page_enhancement', 'upsell_strategy'],
        dependencies: ['budget-analyzer'],
        isPremium: true,
        isEnabled: true,
        created_at: '2026-01-18T11:00:00Z',
        updated_at: '2026-02-01T05:30:00Z',
        task_count: 567,
        success_rate: 93,
        error_count: 40,
        avg_duration_ms: 5200,
        last_execution_at: '2026-02-01T05:30:00Z',
    },
    {
        id: 'agent-007',
        name: 'inventory-sync',
        displayName: 'Inventory Synchronizer',
        description: 'Manages real-time inventory synchronization across platforms',
        role: 'inventory',
        status: 'active',
        capabilities: ['inventory_sync', 'stock_management', 'availability_check', 'sync_automation'],
        dependencies: [],
        isPremium: false,
        isEnabled: true,
        created_at: '2026-01-18T14:00:00Z',
        updated_at: '2026-02-01T08:05:00Z',
        task_count: 3456,
        success_rate: 99,
        error_count: 35,
        avg_duration_ms: 890,
        last_execution_at: '2026-02-01T08:05:00Z',
    },
    {
        id: 'agent-008',
        name: 'pricing-strategist',
        displayName: 'Pricing Strategist',
        description: 'Develops dynamic pricing strategies based on market conditions',
        role: 'strategy',
        status: 'active',
        capabilities: ['dynamic_pricing', 'competitive_pricing', 'margin_optimization', 'demand_forecasting'],
        dependencies: ['competitor-intel', 'budget-analyzer'],
        isPremium: true,
        isEnabled: true,
        created_at: '2026-01-19T10:00:00Z',
        updated_at: '2026-02-01T04:00:00Z',
        task_count: 234,
        success_rate: 91,
        error_count: 21,
        avg_duration_ms: 6800,
        last_execution_at: '2026-02-01T04:00:00Z',
    },
    {
        id: 'agent-009',
        name: 'report-generator',
        displayName: 'Report Generator',
        description: 'Creates comprehensive performance reports and dashboards',
        role: 'reporting',
        status: 'active',
        capabilities: ['report_generation', 'data_visualization', 'insight_extraction', 'kpi_tracking'],
        dependencies: [],
        isPremium: false,
        isEnabled: true,
        created_at: '2026-01-20T08:00:00Z',
        updated_at: '2026-02-01T08:00:00Z',
        task_count: 1890,
        success_rate: 99,
        error_count: 19,
        avg_duration_ms: 4100,
        last_execution_at: '2026-02-01T08:00:00Z',
    },
    {
        id: 'agent-010',
        name: 'trend-analyzer',
        displayName: 'Trend Analyzer',
        description: 'Identifies and analyzes emerging trends and opportunities',
        role: 'analytics',
        status: 'active',
        capabilities: ['trend_detection', 'opportunity_identification', 'trend_prediction', 'market_analysis'],
        dependencies: ['competitor-intel'],
        isPremium: true,
        isEnabled: true,
        created_at: '2026-01-21T09:00:00Z',
        updated_at: '2026-02-01T03:00:00Z',
        task_count: 345,
        success_rate: 92,
        error_count: 28,
        avg_duration_ms: 7500,
        last_execution_at: '2026-02-01T03:00:00Z',
    },
    {
        id: 'agent-011',
        name: 'automation-orchestrator',
        displayName: 'Automation Orchestrator',
        description: 'Coordinates and orchestrates automated workflows across agents',
        role: 'orchestration',
        status: 'active',
        capabilities: ['workflow_orchestration', 'task_scheduling', 'event_handling', 'inter_agent_communication'],
        dependencies: [],
        isPremium: false,
        isEnabled: true,
        created_at: '2026-01-22T10:00:00Z',
        updated_at: '2026-02-01T08:10:00Z',
        task_count: 4567,
        success_rate: 98,
        error_count: 91,
        avg_duration_ms: 450,
        last_execution_at: '2026-02-01T08:10:00Z',
    },
    {
        id: 'agent-012',
        name: 'compliance-monitor',
        displayName: 'Compliance Monitor',
        description: 'Ensures all activities comply with regulations and platform policies',
        role: 'compliance',
        status: 'active',
        capabilities: ['compliance_check', 'policy_enforcement', 'audit_logging', 'risk_assessment'],
        dependencies: [],
        isPremium: true,
        isEnabled: true,
        created_at: '2026-01-23T11:00:00Z',
        updated_at: '2026-02-01T07:00:00Z',
        task_count: 678,
        success_rate: 100,
        error_count: 0,
        avg_duration_ms: 1100,
        last_execution_at: '2026-02-01T07:00:00Z',
    },
    {
        id: 'agent-013',
        name: 'performance-auditor',
        displayName: 'Performance Auditor',
        description: 'Audits and validates agent performance and accuracy',
        role: 'audit',
        status: 'active',
        capabilities: ['performance_audit', 'quality_assurance', 'accuracy_validation', 'benchmark_comparison'],
        dependencies: [],
        isPremium: true,
        isEnabled: true,
        created_at: '2026-01-24T14:00:00Z',
        updated_at: '2026-02-01T02:00:00Z',
        task_count: 234,
        success_rate: 97,
        error_count: 7,
        avg_duration_ms: 8900,
        last_execution_at: '2026-02-01T02:00:00Z',
    },
    {
        id: 'agent-014',
        name: 'sentiment-analyst',
        displayName: 'Sentiment Analyst',
        description: 'Analyzes customer sentiment and brand perception',
        role: 'sentiment',
        status: 'active',
        capabilities: ['sentiment_detection', 'brand_perception', 'feedback_analysis', 'emotion_classification'],
        dependencies: ['customer-engagement'],
        isPremium: false,
        isEnabled: true,
        created_at: '2026-01-25T09:00:00Z',
        updated_at: '2026-02-01T07:55:00Z',
        task_count: 1456,
        success_rate: 95,
        error_count: 73,
        avg_duration_ms: 2100,
        last_execution_at: '2026-02-01T07:55:00Z',
    },
    {
        id: 'agent-015',
        name: 'growth-hacker',
        displayName: 'Growth Hacker',
        description: 'Identifies and executes growth opportunities and strategies',
        role: 'growth',
        status: 'active',
        capabilities: ['growth_strategy', 'viral_potential', 'user_acquisition', 'retention_optimization'],
        dependencies: ['social-optimizer', 'conversion-optimizer'],
        isPremium: true,
        isEnabled: true,
        created_at: '2026-01-26T10:00:00Z',
        updated_at: '2026-02-01T01:00:00Z',
        task_count: 189,
        success_rate: 88,
        error_count: 23,
        avg_duration_ms: 9500,
        last_execution_at: '2026-02-01T01:00:00Z',
    },
    {
        id: 'agent-016',
        name: 'crisis-manager',
        displayName: 'Crisis Manager',
        description: 'Manages crisis situations and negative sentiment escalations',
        role: 'crisis',
        status: 'inactive',
        capabilities: ['crisis_response', 'reputation_management', 'escalation_handling', 'damage_control'],
        dependencies: ['sentiment-analyst', 'customer-engagement'],
        isPremium: true,
        isEnabled: true,
        created_at: '2026-01-27T11:00:00Z',
        updated_at: '2026-01-30T16:00:00Z',
        task_count: 12,
        success_rate: 100,
        error_count: 0,
        avg_duration_ms: 15000,
        last_execution_at: '2026-01-30T16:00:00Z',
    },
];
export const mockDashboardStats = {
    total_agents: 16,
    active_agents: 15,
    premium_agents: 8,
    total_tasks: 20143,
    success_rate: 96,
    tasks_today: 847,
    tasks_this_week: 5234,
    avg_response_time_ms: 3842,
};
export const mockTasks = [
    {
        id: 'task-001',
        agent_id: 'agent-001',
        agent_name: 'content-creator',
        status: 'completed',
        priority: 5,
        created_at: '2026-02-01T08:00:00Z',
        updated_at: '2026-02-01T08:02:34Z',
        started_at: '2026-02-01T08:00:01Z',
        completed_at: '2026-02-01T08:02:34Z',
        result: { content_type: 'instagram_post', engagement_score: 8.5 },
    },
    {
        id: 'task-002',
        agent_id: 'agent-003',
        agent_name: 'budget-analyzer',
        status: 'running',
        priority: 8,
        created_at: '2026-02-01T08:10:00Z',
        updated_at: '2026-02-01T08:10:00Z',
        started_at: '2026-02-01T08:10:01Z',
        completed_at: null,
    },
    {
        id: 'task-003',
        agent_id: 'agent-011',
        agent_name: 'automation-orchestrator',
        status: 'pending',
        priority: 5,
        created_at: '2026-02-01T08:15:00Z',
        updated_at: '2026-02-01T08:15:00Z',
        started_at: null,
        completed_at: null,
    },
    {
        id: 'task-004',
        agent_id: 'agent-002',
        agent_name: 'social-optimizer',
        status: 'completed',
        priority: 7,
        created_at: '2026-02-01T07:30:00Z',
        updated_at: '2026-02-01T07:31:50Z',
        started_at: '2026-02-01T07:30:02Z',
        completed_at: '2026-02-01T07:31:50Z',
        result: { optimizations_applied: 3, projected_improvement: 12.5 },
    },
    {
        id: 'task-005',
        agent_id: 'agent-007',
        agent_name: 'inventory-sync',
        status: 'failed',
        priority: 9,
        created_at: '2026-02-01T07:45:00Z',
        updated_at: '2026-02-01T07:45:30Z',
        started_at: '2026-02-01T07:45:01Z',
        completed_at: '2026-02-01T07:45:30Z',
        error: 'Connection timeout to Shopify API',
    },
];
export const mockTaskChartData = [
    { day: 'Mon', completed: 124, failed: 4, pending: 12 },
    { day: 'Tue', completed: 156, failed: 6, pending: 8 },
    { day: 'Wed', completed: 143, failed: 3, pending: 15 },
    { day: 'Thu', completed: 178, failed: 5, pending: 11 },
    { day: 'Fri', completed: 192, failed: 7, pending: 9 },
    { day: 'Sat', completed: 89, failed: 2, pending: 6 },
    { day: 'Sun', completed: 95, failed: 3, pending: 8 },
];
export const mockAgentPerformanceData = [
    { name: 'Content Creator', tasks: 1254, success_rate: 97 },
    { name: 'Social Optimizer', tasks: 892, success_rate: 95 },
    { name: 'Budget Analyzer', tasks: 1567, success_rate: 98 },
    { name: 'Customer Engagement', tasks: 2341, success_rate: 96 },
    { name: 'Inventory Sync', tasks: 3456, success_rate: 99 },
    { name: 'Report Generator', tasks: 1890, success_rate: 99 },
    { name: 'Automation Orchestrator', tasks: 4567, success_rate: 98 },
];
export const agentRoles = [
    { code: 'content_creation', name: 'Content Creator', description: 'Generates and optimizes content' },
    { code: 'optimization', name: 'Optimizer', description: 'Optimizes campaigns and performance' },
    { code: 'analytics', name: 'Analyst', description: 'Analyzes data and metrics' },
    { code: 'intelligence', name: 'Intelligence', description: 'Gathers competitive and market intelligence' },
    { code: 'engagement', name: 'Engagement', description: 'Manages customer engagement' },
    { code: 'conversion', name: 'Converter', description: 'Optimizes conversions' },
    { code: 'inventory', name: 'Inventory Manager', description: 'Manages inventory synchronization' },
    { code: 'strategy', name: 'Strategist', description: 'Develops strategies' },
    { code: 'reporting', name: 'Reporter', description: 'Generates reports' },
    { code: 'orchestration', name: 'Orchestrator', description: 'Orchestrates workflows' },
    { code: 'compliance', name: 'Compliance Officer', description: 'Ensures compliance' },
    { code: 'audit', name: 'Auditor', description: 'Audits performance' },
    { code: 'sentiment', name: 'Sentiment Analyst', description: 'Analyzes sentiment' },
    { code: 'growth', name: 'Growth Specialist', description: 'Drives growth' },
    { code: 'crisis', name: 'Crisis Manager', description: 'Manages crises' },
];
